services:
  - type: web
    name: todo-api
    runtime: docker
    repo: https://github.com/ratnakarchakkapalli/todo-api
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3000
